# Generated by Django 4.2.13 on 2024-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('idblock', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CausasBeneficas',
            fields=[
                ('idcausas_beneficas', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_causa', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'causas_beneficas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDonacion',
            fields=[
                ('idestado_donacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_donacioncol', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'estado_donacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idtransaccion', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('monto', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('idwallet', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'wallet',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
